# Generated by Django 5.1.15 on 2026-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat Amount (₹)'), ('percentage', 'Percentage (%)')], default='flat', max_length=20),
        ),
    ]
