# Generated by Django 5.1.15 on 2026-08-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_category_requires_compatibility_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'device brand',
                'verbose_name_plural': 'device brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='compatibility.devicebrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='catalog.category')),
            ],
            options={
                'verbose_name': 'device model',
                'verbose_name_plural': 'device models',
                'ordering': ['brand__name', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text="Optional note, e.g., 'High Yield Cartridge' or '65W Power Adapter'", max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_mappings', to='catalog.product')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_mappings', to='compatibility.devicemodel')),
            ],
            options={
                'verbose_name': 'compatibility mapping',
                'verbose_name_plural': 'compatibility mappings',
                'ordering': ['device_model', 'product'],
                'unique_together': {('device_model', 'product')},
            },
        ),
    ]
