# Generated by Django 5.1.15 on 2026-08-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='cod', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Collection'), ('collected', 'Payment Collected'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
