# Generated by Django 5.1.15 on 2026-08-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_category_requires_compatibility_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total physical stock quantity in warehouse.')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Stock currently reserved for pending orders.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert threshold for low stock warnings.')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'stock record',
                'verbose_name_plural': 'stock records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
