# Generated by Django 5.1.15 on 2026-08-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='requires_compatibility_mapping',
            field=models.BooleanField(default=False, help_text='Set to true for categories requiring host device compatibility lookup (e.g. Cartridges, Batteries).'),
        ),
    ]
